apiVersion: v1
kind: Secret
metadata:
  name: grade-submission-secret
  namespace: grade-submission
type: Opaque
data:
  MONGODB_USER: 'YWRtaW4='
  MONGODB_PASSWORD: 'bXlwYXNzd29yZDEyMw=='
  MONGO_INITDB_ROOT_USERNAME: 'YWRtaW4='
  MONGO_INITDB_ROOT_PASSWORD: 'bXlwYXNzd29yZDEyMw=='
